sudo: false
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- yarn add polymer-cli
- polymer install --variants
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: HqY/RSY+ADijU/ODd4KKCCo0a3DeOcCO+Rj0jaxgzHBFrvA782Zt6FXcDOJMzvvzSMhlPMI9k/63lAORzqVdcLayt5GzlkskARz4jJecc3UCi9O4QynjK74Lg91z+3QGlo6SxpKt97Equh5z1SiaJvmnvTAtwlzLB1Tey6r6sR6NO1zthuResRqxXV9X6byoWoty69YeTYdNxx14YkH1YFDUvnctrg2ba+3gOA9H9IAFc3V5/hP9RRgaNIhE/6T/W8yAVwpNCFdDhwsacXMCUxAtHyge5E0T5taIlZ2wwJnvv9qXXYcqYsiOihDQdRtlh1bkRPxWk6M+oP8JmeIt5kD7MIRxX4fG8EaSJBCGtK8ksq0CH2xuUMwrDW2l0WVWU7P5JemtSR/1+g+hd6STpx5Zrp7T0EtGM6uCZp66buse8/5oyWbRM8xRq0qjpfHm9u8V1i608EL0kNE16SdFFBnjg5W4pJh/H55dZOzrzTVhZ/vvH12j0rcrphPxb6S8kmzNkUJ9832kFUAQkeMzRzDxmxbVlnxaU7cZjNuIoPBb07HFxcPi837yVordRU+DtcXf0nOmW69JDfQCi59nRs+TkSf6VHUhLw154nqefmUS2+CM8Khqr4/m5UvKs2hb1sD6if1G211sEw90anFyGUcs9oqRMEY+6rxR5k8QXIs=
  - secure: IbV149YCJX/X23MCBse/zzKZCvYWZKqrCILY7GeqSEkqFB3bFu+KlFYFuYDoyZtzY5FoW2iqOYkbLa4585l8GsMHBskeRY4SG2xwdxK0lzhNjxIjO6vajOvUmIVloTrCHpLaT3yr2cTIAcZKYzrGVb/mJeY0yZdI6zW9RT0UiUhcCQ64+6grQF2JM5PSE3LOfP8Ey6KwgTj+lU2oCmr1/m5NZ1ouAuLrGlQyIN5FMSo/hrvIiYsi1VGzgM7rioAseWUvy097v1qvKwOGlmW2oF18bqyCUIz6ArfxnKWVf1WDylVOV3nF0WJ7shNdRvexaR95SJtWbbddaNXr8UJIB1uvw9q0Q8UvY4Xz/9Bs0z2w5V1zp1i+65oPY14sVaCqge4UD/CAPy7Pzo+3akdjrtrP+ugLaOFL9b6ntU4+G6hxvUgQQCYI8CaTKjhReI/rTZRlJtsRQs/pJzd+wYeR+Uw/7qpKOFCwC9jHapPMIfN/d7SvY2XXTfCQveE/mj2aKPDGWD3dALiPYPLv6mI2Qz/OkLl2uvEowCP5vZHEgLqfcirE0KsILmD6CfaRgAkFXtiV2xeK4EgXnidHy5k+zFA3s/mdLILpGCTV6pTlvnPxVqrntUhayA+xTcCF8uCve0jZNggpNLl7o66sBJt6t56BfyW6oNifz4/NO8sbg60=
  - secure: WqvnvsmdYXcatHwIIv9xSeaBUFUeZJaPYwoXaj4H601zxvo4SMJqbVxpshENECsrIiVCCCKIYagxq818dJfOiD4RAj+UnxCsyW19xNfPgvoh8C86Azua8WkX3NY2fRye6x6XEJ0PpzxPZMh9wP93qpIBzlCMqB8CyAuKovwyjSmhCUxOgSHhzNicYgjEQiH+fRAdr5XEa1prFHF0yw3bI2orclhUBuFJsbmqIf0IBU9smw23sw5aUGSNV+V1jHrPfAzT5OUQyYu7V9vLu5vk/TY24rQ2z3x3JLi/jB+mXucXk97S4MIJ6lYYD5Ol+RUVrTQUcqhtlxcauQnZCjr626cUATaOJI9mbEH7f/08gYktyS7b+HCenOL0mksw1TzlEOJio7xdCG++1RIctx7SqwyZCsDLMLgwxOuqRCDnrIbecuBsuglIRhB9wk7VLnYZkqccGPYv1/HG5Sz5iSiAH9YHNRghz25JfC8Wq8l8JSkupSFRBpH0p2Yvuq9mx5BVC9anY/RTOwvGsvb+biyKsjZ4SWHJ7VUce/IFan4GfOKc8FHE8N0hJzmSxcAMbO1jJCuQpl79niq2VDD8et/luPfHPXddIPJB3n5FxppovBZPtQSPvuCYxx8jX6Rl6IPUgt128S+iYJ4rPtbr/E/683hWoLbFP7qisLVoRfIMa5o=
  - secure: YkyDl5+N81afo5dBN+QAD0L06gQlO1X7qzAvsB+nj2+5bXz3TNYcJXmZzhmTeQiy1oPdgmNdcZnOX9ysQ6CXCeUJOm8dFIu8PrGhcFCyhyd1SQWDdGW5CTgpsoj4BaD6AYFYaCofEiocwL0L9inoteIrZ6ARuL+okGnJw9xUS7z2ecHJ1B15m+2RO4rTI4bK3lNOc0MdYqem3E6R4rdsM6c50orLyFD+w5w4Yyg7l9LgjQiFePvxNqoFIXQX+qNMrj1eEhl4fUlCML6gdrli38ZyumcYQOISC2iJdkhdwNKhqxEeRro/SFUhQiyYDV0zeuDaOMcRkk/iBqG8kwAgtvxswxQiCNGxnA8eUnH1aflA9pbKtoQSu1es9gnFAf1BE8RVHARAqgravxG/9o/OKn5YRP1C7oRmK9Sx/tViQLtKPQ9ntD+boxqgmdOBd2SpfXXtSAWXQ0RV/58mg52CrxGLqvYFYzrcN0oZ14YKHjAQiGXWlDwzY1URXRSO+GCSU3aAH/J2NvwRw6PnMrEUQLvGbGwgSg6Ey+AzzYopd64sBLRHXstv0NJPG5+aiIbsTInE/g3rhvxvq93N5/c1yzIixezqia9meohZ5uIA3QxRcF0/Edaso21ujROtCx6anGrXutYZnGMGT5QPvydWOf8+PPGVRozvnXeTK/bIwiU=
