sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
env:
  global:
  - secure: cuCOV6/+Ga+L/N9ag2aQH5q4c/r4VYIbH7XOlDK4oo5UJeI4cqODGVZ3behfMyXheTCixrKjQ2M1qtUEOvTJGnC6bROSxEvmBJ+FV5BfBuzXkuDB+W8Lj6pmK8XoVD8eL6uMubaZuikEe/gV/Ln+pMmixgafzgelNG0yxPU9TBzE+V9nqQeEMmyj7D2VGI90F3v8yP+ndysD1Mv9+dpLVsWsVXW85U5phBbHkstRsTkWV8sCCMHklVVVkG/U1xwH/nNnDB7O+nZIMPcCCYzOZfhmML9sAI1bb7XO8+KjX/4haayEjUK0cme3bibrtLIjz83K9W2Ep1gSxudSBvwkJ4fAkRCDb+DyVIZLJxlfv6/1jBtFtndSoUTLRmSQUK+J0/iIBPc5FQLtxZ8lI82z/Xe6sCibPavteOPlCsH4c686TJEMy/si8LiOvkCdii0GzYkdLpYW+dk0CHwQK4Nu02nIKxc830Hx+dLIkPYxAp6AIDG0pRID8sJEgVdgvyngI94C7Hun9hPTeGgQcxyEwPtXTvpO8XS9dbr1bz83QFNaCNEuS9HBu/fNMJmcVjAAGjt3VQ7b/DWFkyatci9y1VhdmfUkDePk731NwMn/+qfo+2sVsOEEbTFzj9RudNnN5rN4ICR7p0oFGCGcjW1+kD7nqb5EnAANjrzRiRDAank=
  - secure: r0kpviKELD8LZzdW35H1gKXesqPX5JEd/88Y1WY1+DnDSni7PvpcAWK3R4Wrwm/mNkyjIvuDKZMNLDm83rvOf1G/DONOh2PhlwEIsjvGmWN+JYFpJqJvFp8fgaHET+zwkRiv9Mt1eulkyH1qwlWjmJGsSJzVVNbKHkjl4ahGRIKktzmBWKiFqVXhxhUBr2moR4MU89tABRCckDjLqdUmF8a/q2KuGmLRdqqmqwGupVbS1/jYrmY0Ruh+uHmXNbxzcYX0dDFBVBrF8N7QHSfTPmbtPvcnDsoPsDQRoMblPdUhxnaQbTHMLahp1bgm15Dwsrzy8nKcSKvZSup1/jlJyS6Ik7Thx5QZAgpVyi3uBmPNBgEHO7C/sPu1fEkhMRg2KYZiG6sUzqeCx8zF+SH1GwAWCPLC2e5smXIAMpabgrjyJA9p1lwVGapbDcZgS6u1N2pT0SNziFUmtaJ7VfPg1PlExQmZlGXZSLOrm8YScq1hD3BGwDrwWWKtAtPEJBdtUDc9RNTK9kKOz2Scs5TBSAJCNi/ytXf6s585S+cZQpIeNUkIdMxGuqdqH9+A/436pAUYSfG1ffiM10ssLlRzFAPppHd3SNcGMIY7WQ78Plfwor+t1tCkDuvKKxnqjkBQMOz+Cf6ACNXQAkBsYK+tyt/NtBkSjP2HaHe5M9QKqZE=
before_install:
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$password" -in id_rsa.enc -out deploy_key -d; fi
after_success:
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
