sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
env:
  global:
    secure: cuCOV6/+Ga+L/N9ag2aQH5q4c/r4VYIbH7XOlDK4oo5UJeI4cqODGVZ3behfMyXheTCixrKjQ2M1qtUEOvTJGnC6bROSxEvmBJ+FV5BfBuzXkuDB+W8Lj6pmK8XoVD8eL6uMubaZuikEe/gV/Ln+pMmixgafzgelNG0yxPU9TBzE+V9nqQeEMmyj7D2VGI90F3v8yP+ndysD1Mv9+dpLVsWsVXW85U5phBbHkstRsTkWV8sCCMHklVVVkG/U1xwH/nNnDB7O+nZIMPcCCYzOZfhmML9sAI1bb7XO8+KjX/4haayEjUK0cme3bibrtLIjz83K9W2Ep1gSxudSBvwkJ4fAkRCDb+DyVIZLJxlfv6/1jBtFtndSoUTLRmSQUK+J0/iIBPc5FQLtxZ8lI82z/Xe6sCibPavteOPlCsH4c686TJEMy/si8LiOvkCdii0GzYkdLpYW+dk0CHwQK4Nu02nIKxc830Hx+dLIkPYxAp6AIDG0pRID8sJEgVdgvyngI94C7Hun9hPTeGgQcxyEwPtXTvpO8XS9dbr1bz83QFNaCNEuS9HBu/fNMJmcVjAAGjt3VQ7b/DWFkyatci9y1VhdmfUkDePk731NwMn/+qfo+2sVsOEEbTFzj9RudNnN5rN4ICR7p0oFGCGcjW1+kD7nqb5EnAANjrzRiRDAank=
